#!/usr/bin/env bash

CHANGED_FILES=$(git --no-pager diff --name-only --cached --diff-filter=ACMR -- '*.py')

if [ -n "$CHANGED_FILES" ]; then
    poetry run ruff check --force-exclude --fix --exit-non-zero-on-fix $CHANGED_FILES
fi
