[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Nikolay Bely <belyynikolay@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
celery = { version = "5.3.4", extras = ["eventlet", "redis"] }
django = "4.2.5"
django-celery-beat = "2.5.0"
django-celery-results = "2.5.1"
django-jinja = "2.11.0"
django-minio-storage = "0.5.7"
django-redisboard = "8.4.0"
docutils = "0.20.1"
eventlet = "0.33.3"
gunicorn = { version = "21.2.0", extras = ["eventlet"] }
jinja2 = "3.1.2"
pillow = "10.0.1"
psycopg = { extras = ["binary"], version = "3.1.12" }
whitenoise = { extras = ["brotli"], version = "6.5.0" }
django-filter = "23.3"

[tool.poetry.group.dev.dependencies]
black = "23.9.1"
debugpy = "1.8.0"
django-debug-toolbar = "4.2.0"
djlint = "1.34.0"
pre-commit = "3.4.0"
pyinstrument = "4.5.3"
ruff = "0.0.292"

[tool.black]
target-version = ["py311"]
# verbose = true

[tool.djlint]
ignore = "H006,H030,H031"
include = "H017,H035"
extend_exclude = "profiles/"
indent = 2
blank_line_after_tag = "load,extends"
profile = "jinja"
max_line_length = 80
format_attribute_template_tags = true
use_gitignore = true

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md#type-check-diagnostics-settings
reportGeneralTypeIssues = false

[tool.ruff]
select = [
    "E",
    "F",
    "W",
    "C",
    "I",
    "D",
    "UP",
    "YTT",
    #"ANN",
    "B",
    "COM",
    "C4",
    "PT",
    "RET",
    "SIM",
    "ARG",
    "PTH",
    "PL",
    "TRY",
    "RUF",
]
respect-gitignore = true
src = ["server"]
target-version = "py311"

[tool.ruff.flake8-pytest-style]
fixture-parentheses = true
mark-parentheses = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"**/migrations/*" = ["ANN", "D100", "D101", "RUF012"]

[tool.ruff.pydocstyle]
convention = "google"
