services:
  pgadmin:
    container_name: djc_pgadmin4
    # env_file: ../.env
    image: dpage/pgadmin4:8.6
    volumes:
      - ../tools/pgadmin4/servers.json:/pgadmin4/servers.json:ro
      - ../tools/pgadmin4/home/:/home/:rw
      - djc_pgadmin4_data:/var/lib/pgadmin:rw
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_MFA_ENABLED: "False"
      PGADMIN_CONFIG_ENABLE_PSQL: "True"
      PGADMIN_CONFIG_STORAGE_DIR: ~
      # Default user for desktop mode (SERVER_MODE = False)
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      # Default password for desktop mode (SERVER_MODE = False)
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
      PGADMIN_LISTEN_PORT: 15432
    tty: true
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'djc_postgres:5432:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    # networks:
    #   private_network:
    #     ipv4_address: 172.20.0.16

volumes:
  djc_pgadmin4_data:
    external: true
