services:
  dozzle:
    container_name: djc_dozzle
    image: docker.io/amir20/dozzle:v6.6.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_ENABLE_ACTIONS=true
