services:
  djc_server:
    build:
      context: ..
      dockerfile: ./docker/server.dockerfile
      args:
        - DEBUG=${DJANGO_DEBUG}
    container_name: djc_server
    env_file: ../.env
    user: ${CURRENT_UID}
    restart: on-failure
    volumes:
      - ..:/app
      - /app/.venv
    ports:
      - 5678:5678
    links:
      - djc_redis
      - djc_postgres
    depends_on:
      - djc_redis
      - djc_postgres
      - djc_minio
    command: >
      /app/docker/entrypoint-back.sh

  djc_postgres:
    image: postgres:16.3-bookworm
    container_name: djc_postgres
    hostname: postgres
    env_file: ../.env
    restart: on-failure
    volumes:
      - djc_db_data:/var/lib/postgresql/data

  djc_redis:
    image: redis:7.2.5-bookworm
    container_name: djc_redis
    hostname: redis
    restart: on-failure

  djc_celery_worker:
    image: docker-djc_server:latest
    container_name: djc_celery_worker
    env_file: ../.env
    user: ${CURRENT_UID}
    restart: on-failure
    working_dir: /app/server
    volumes:
      - ..:/app
      - /app/.venv
    links:
      - djc_redis
      - djc_postgres
    depends_on:
      - djc_redis
      - djc_postgres
      - djc_server
      - djc_minio
    # deploy:
    #   mode: replicated
    #   replicas: 6
    command: >
      /app/docker/entrypoint-worker.sh

  djc_celery_beat:
    image: docker-djc_server:latest
    container_name: djc_celery_beat
    env_file: ../.env
    user: ${CURRENT_UID}
    restart: on-failure
    working_dir: /app/server
    volumes:
      - ..:/app
      - /app/.venv
    links:
      - djc_redis
      - djc_postgres
    depends_on:
      - djc_redis
      - djc_postgres
      - djc_server
      - djc_minio
    command: >
      /app/docker/entrypoint-beat.sh

  djc_minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: djc_minio
    hostname: minio
    volumes:
      - djc_s3_data:/data
    environment:
      - MINIO_BROWSER_REDIRECT_URL=https://minio.localhost/f75a0d8/
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    command: >
      server /data --console-address ":9001"

  djc_caddy:
    image: caddy:2.7.6
    container_name: djc_caddy
    hostname: caddy
    restart: unless-stopped
    volumes:
      - ../caddy/dev.caddyfile:/etc/caddy/Caddyfile:ro
      - djc_caddy_data:/data
      - djc_caddy_config:/config
      - ../staticfiles:/static:ro
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # http/3
      - "2019:2019" # trust/untrust support
    environment:
      - CADDY_ADMIN=0.0.0.0:2019

volumes:
  djc_caddy_data:
    external: true
  djc_caddy_config:
    external: true
  djc_db_data:
    external: true
  djc_s3_data:
    external: true
