version: "3.8"

services:
  dj_back:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - DEBUG=${DJANGO_DEBUG}
    container_name: dj_back
    env_file: ../.env
    user: ${CURRENT_UID}
    restart: on-failure
    volumes:
      - ..:/app
      - /app/.venv
    ports:
      - 8000:8000
      - 5678:5678
    links:
      - dj_redis
      - dj_postgres
    depends_on:
      - dj_redis
      - dj_postgres
      - dj_minio
    command: >
      /app/docker/entrypoint-back.sh

  dj_postgres:
    image: postgres:15.4
    container_name: dj_postgres
    hostname: postgres
    env_file: ../.env
    restart: on-failure
    volumes:
      - dj_db_data:/var/lib/postgresql/data

  dj_redis:
    image: redis:7.2
    container_name: dj_redis
    hostname: redis
    restart: on-failure

  dj_celery_worker:
    image: docker-dj_back:latest
    container_name: dj_celery_worker
    env_file: ../.env
    user: ${CURRENT_UID}
    restart: on-failure
    working_dir: /app/src
    volumes:
      - ..:/app
      - /app/.venv
    links:
      - dj_redis
      - dj_postgres
    depends_on:
      - dj_redis
      - dj_postgres
      - dj_back
      - dj_minio
    # deploy:
    #   mode: replicated
    #   replicas: 6
    command: >
      /app/docker/entrypoint-worker.sh

  dj_celery_beat:
    image: docker-dj_back:latest
    container_name: dj_celery_beat
    env_file: ../.env
    user: ${CURRENT_UID}
    restart: on-failure
    working_dir: /app/src
    volumes:
      - ..:/app
      - /app/.venv
    links:
      - dj_redis
      - dj_postgres
    depends_on:
      - dj_redis
      - dj_postgres
      - dj_back
      - dj_minio
    command: >
      /app/docker/entrypoint-beat.sh

  dj_minio:
    image: minio/minio:RELEASE.2023-08-31T15-31-16Z
    container_name: dj_minio
    hostname: minio
    volumes:
      - dj_s3_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    command: >
      server /data --console-address ":9001"

volumes:
  dj_db_data:
    external: true
  dj_s3_data:
    external: true
