# Generated by Django 4.2.4 on 2023-08-30 14:55

from django.db import migrations, models


def init_redisboard(apps, _schema_editor) -> None:
    """Django Redisboard init with default cache server.

    Args:
        apps: historical versions of all models
        _schema_editor: use to manually effect database schema changes
    """
    RedisServer = apps.get_model("redisboard", "RedisServer")
    RedisServer(
        label="Django Redis Cache",
        url="redis://dj_redis:6379",
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("redisboard", "0005_config"),
    ]

    operations = [
        migrations.RunPython(
            code=init_redisboard,
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField(auto_now_add=True, verbose_name="When")),
                (
                    "levelname",
                    models.TextField(editable=False, verbose_name="Level name"),
                ),
                (
                    "shortmessage",
                    models.TextField(editable=False, verbose_name="Short message"),
                ),
                ("message", models.TextField(editable=False, verbose_name="Message")),
                (
                    "request_repr",
                    models.TextField(
                        editable=False,
                        verbose_name="Request representation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log entry",
                "verbose_name_plural": "Log entries",
            },
        ),
    ]
