# Generated by Django 4.2.4 on 2023-08-30 04:30


from django.db import migrations


def init_redisboard(apps, _schema_editor) -> None:
    """Django Redisboard init with default cache server.

    Args:
        apps: historical versions of all models
        _schema_editor: use to manually effect database schema changes
    """
    RedisServer = apps.get_model("redisboard", "RedisServer")
    redis_cache = RedisServer(label="Django Redis Cache", url="redis://dj_redis:6379")
    redis_cache.save()


class Migration(migrations.Migration):
    """Initital migration for solution."""

    dependencies = []

    operations = [
        migrations.RunPython(init_redisboard),
    ]
